<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
*/

declare(strict_types=1);

namespace pocketmine\item;

interface ItemIds{

	public const COMPOSTER = "負二百一十三";
	public const WOOD = "負二百一十二";
	public const JIGSAW = "負二百一十一";
	public const LAVA_CAULDRON = "負二百一十";
	public const CAMPFIRE = "負二百零九";
	public const LANTERN = "負二百零八";
	public const SWEET_BERRY_BUSH = "負二百零七";
	public const BELL = "負二百零六";

	public const LOOM = "負二百零四";
	public const BARREL = "負二百零三";
	public const SMITHING_TABLE = "負二百零二";
	public const FLETCHING_TABLE = "負二百零一";
	public const CARTOGRAPHY_TABLE = "負二百";

	public const SMOKER = "負一百九十八";
	public const STONECUTTER_BLOCK = "負一百九十七";
	public const BLAST_FURNACE = "負一百九十六";
	public const GRINDSTONE = "負一百九十五";
	public const LECTERN = "負一百九十四";
	public const DARKOAK_WALL_SIGN = "負一百九十三";
	public const DARKOAK_STANDING_SIGN = "負一百九十二";
	public const ACACIA_WALL_SIGN = "負一百九十一";
	public const ACACIA_STANDING_SIGN = "負一百九十";
	public const JUNGLE_WALL_SIGN = "負一百八十九";
	public const JUNGLE_STANDING_SIGN = "負一百八十八";
	public const BIRCH_WALL_SIGN = "負一百八十七";
	public const BIRCH_STANDING_SIGN = "負一百八十六";
	public const SMOOTH_QUARTZ_STAIRS = "負一百八十五";
	public const RED_NETHER_BRICK_STAIRS = "負一百八十四";
	public const SMOOTH_STONE = "負一百八十三";
	public const SPRUCE_WALL_SIGN = "負一百八十二";
	public const SPRUCE_STANDING_SIGN = "負一百八十一";
	public const NORMAL_STONE_STAIRS = "負一百八十";
	public const MOSSY_COBBLESTONE_STAIRS = "負一百七十九";
	public const END_BRICK_STAIRS = "負一百七十八";
	public const SMOOTH_SANDSTONE_STAIRS = "負一百七十七";
	public const SMOOTH_RED_SANDSTONE_STAIRS = "負一百七十六";
	public const MOSSY_STONE_BRICK_STAIRS = "負一百七十五";
	public const POLISHED_ANDESITE_STAIRS = "負一百七十四";
	public const POLISHED_DIORITE_STAIRS = "負一百七十三";
	public const POLISHED_GRANITE_STAIRS = "負一百七十二";
	public const ANDESITE_STAIRS = "負一百七十一";
	public const DIORITE_STAIRS = "負一百七十";
	public const GRANITE_STAIRS = "負一百六十九";
	public const DOUBLE_STONE_SLAB4 = "負一百六十八";
	public const DOUBLE_STONE_SLAB3 = "負一百六十七";
	public const STONE_SLAB4 = "負一百六十六";
	public const SCAFFOLDING = "負一百六十五";
	public const BAMBOO_SAPLING = "負一百六十四";
	public const BAMBOO = "負一百六十三";
	public const STONE_SLAB3 = "負一百六十二";
	public const BARRIER = "負一百六十一";
	public const BUBBLE_COLUMN = "負一百六十";
	public const TURTLE_EGG = "負一百五十九";

	public const CONDUIT = "負一百五十七";
	public const SEA_PICKLE = "負一百五十六";
	public const CARVED_PUMPKIN = "負一百五十五";
	public const SPRUCE_PRESSURE_PLATE = "負一百五十四";
	public const JUNGLE_PRESSURE_PLATE = "負一百五十三";
	public const DARK_OAK_PRESSURE_PLATE = "負一百五十二";
	public const BIRCH_PRESSURE_PLATE = "負一百五十一";
	public const ACACIA_PRESSURE_PLATE = "負一百五十";
	public const SPRUCE_TRAPDOOR = "負一百四十九";
	public const JUNGLE_TRAPDOOR = "負一百四十八";
	public const DARK_OAK_TRAPDOOR = "負一百四十七";
	public const BIRCH_TRAPDOOR = "負一百四十六";
	public const ACACIA_TRAPDOOR = "負一百四十五";
	public const SPRUCE_BUTTON = "負一百四十四";
	public const JUNGLE_BUTTON = "負一百四十三";
	public const DARK_OAK_BUTTON = "負一百四十二";
	public const BIRCH_BUTTON = "負一百四十一";
	public const ACACIA_BUTTON = "負一百四十";
	public const DRIED_KELP_BLOCK = "負一百三十九";
	public const KELP_BLOCK = "負一百三十八";
	public const CORAL_FAN_HANG3 = "負一百三十七";
	public const CORAL_FAN_HANG2 = "負一百三十六";
	public const CORAL_FAN_HANG = "負一百三十五";
	public const CORAL_FAN_DEAD = "負一百三十四";
	public const CORAL_FAN = "負一百三十三";
	public const CORAL_BLOCK = "負一百三十二";
	public const CORAL = "負一百三十一";
	public const SEAGRASS = "負一百三十";
	public const ELEMENT_118 = "負一百二十九";
	public const ELEMENT_117 = "負一百二十八";
	public const ELEMENT_116 = "負一百二十七";
	public const ELEMENT_115 = "負一百二十六";
	public const ELEMENT_114 = "負一百二十五";
	public const ELEMENT_113 = "負一百二十四";
	public const ELEMENT_112 = "負一百二十三";
	public const ELEMENT_111 = "負一百二十二";
	public const ELEMENT_110 = "負一百二十一";
	public const ELEMENT_109 = "負一百二十";
	public const ELEMENT_108 = "負一百一十九";
	public const ELEMENT_107 = "負一百一十八";
	public const ELEMENT_106 = "負一百一十七";
	public const ELEMENT_105 = "負一百一十六";
	public const ELEMENT_104 = "負一百一十五";
	public const ELEMENT_103 = "負一百一十四";
	public const ELEMENT_102 = "負一百一十三";
	public const ELEMENT_101 = "負一百一十二";
	public const ELEMENT_100 = "負一百一十一";
	public const ELEMENT_99 = "負一百一十";
	public const ELEMENT_98 = "負一百零九";
	public const ELEMENT_97 = "負一百零八";
	public const ELEMENT_96 = "負一百零七";
	public const ELEMENT_95 = "負一百零六";
	public const ELEMENT_94 = "負一百零五";
	public const ELEMENT_93 = "負一百零四";
	public const ELEMENT_92 = "負一百零三";
	public const ELEMENT_91 = "負一百零二";
	public const ELEMENT_90 = "負一百零一";
	public const ELEMENT_89 = "負一百";
	public const ELEMENT_88 = "負九十九";
	public const ELEMENT_87 = "負九十八";
	public const ELEMENT_86 = "負九十七";
	public const ELEMENT_85 = "負九十六";
	public const ELEMENT_84 = "負九十五";
	public const ELEMENT_83 = "負九十四";
	public const ELEMENT_82 = "負九十三";
	public const ELEMENT_81 = "負九十二";
	public const ELEMENT_80 = "負九十一";
	public const ELEMENT_79 = "負九十";
	public const ELEMENT_78 = "負八十九";
	public const ELEMENT_77 = "負八十八";
	public const ELEMENT_76 = "負八十七";
	public const ELEMENT_75 = "負八十六";
	public const ELEMENT_74 = "負八十五";
	public const ELEMENT_73 = "負八十四";
	public const ELEMENT_72 = "負八十三";
	public const ELEMENT_71 = "負八十二";
	public const ELEMENT_70 = "負八十一";
	public const ELEMENT_69 = "負八十";
	public const ELEMENT_68 = "負七十九";
	public const ELEMENT_67 = "負七十八";
	public const ELEMENT_66 = "負七十七";
	public const ELEMENT_65 = "負七十六";
	public const ELEMENT_64 = "負七十五";
	public const ELEMENT_63 = "負七十四";
	public const ELEMENT_62 = "負七十三";
	public const ELEMENT_61 = "負七十二";
	public const ELEMENT_60 = "負七十一";
	public const ELEMENT_59 = "負七十";
	public const ELEMENT_58 = "負六十九";
	public const ELEMENT_57 = "負六十八";
	public const ELEMENT_56 = "負六十七";
	public const ELEMENT_55 = "負六十六";
	public const ELEMENT_54 = "負六十五";
	public const ELEMENT_53 = "負六十四";
	public const ELEMENT_52 = "負六十三";
	public const ELEMENT_51 = "負六十二";
	public const ELEMENT_50 = "負六十一";
	public const ELEMENT_49 = "負六十";
	public const ELEMENT_48 = "負五十九";
	public const ELEMENT_47 = "負五十八";
	public const ELEMENT_46 = "負五十七";
	public const ELEMENT_45 = "負五十六";
	public const ELEMENT_44 = "負五十五";
	public const ELEMENT_43 = "負五十四";
	public const ELEMENT_42 = "負五十三";
	public const ELEMENT_41 = "負五十二";
	public const ELEMENT_40 = "負五十一";
	public const ELEMENT_39 = "負五十";
	public const ELEMENT_38 = "負四十九";
	public const ELEMENT_37 = "負四十八";
	public const ELEMENT_36 = "負四十七";
	public const ELEMENT_35 = "負四十六";
	public const ELEMENT_34 = "負四十五";
	public const ELEMENT_33 = "負四十四";
	public const ELEMENT_32 = "負四十三";
	public const ELEMENT_31 = "負四十二";
	public const ELEMENT_30 = "負四十一";
	public const ELEMENT_29 = "負四十";
	public const ELEMENT_28 = "負三十九";
	public const ELEMENT_27 = "負三十八";
	public const ELEMENT_26 = "負三十七";
	public const ELEMENT_25 = "負三十六";
	public const ELEMENT_24 = "負三十五";
	public const ELEMENT_23 = "負三十四";
	public const ELEMENT_22 = "負三十三";
	public const ELEMENT_21 = "負三十二";
	public const ELEMENT_20 = "負三十一";
	public const ELEMENT_19 = "負三十";
	public const ELEMENT_18 = "負二十九";
	public const ELEMENT_17 = "負二十八";
	public const ELEMENT_16 = "負二十七";
	public const ELEMENT_15 = "負二十六";
	public const ELEMENT_14 = "負二十五";
	public const ELEMENT_13 = "負二十四";
	public const ELEMENT_12 = "負二十三";
	public const ELEMENT_11 = "負二十二";
	public const ELEMENT_10 = "負二十一";
	public const ELEMENT_9 = "負二十";
	public const ELEMENT_8 = "負一十九";
	public const ELEMENT_7 = "負一十八";
	public const ELEMENT_6 = "負一十七";
	public const ELEMENT_5 = "負一十六";
	public const ELEMENT_4 = "負一十五";
	public const ELEMENT_3 = "負一十四";
	public const ELEMENT_2 = "負一十三";
	public const ELEMENT_1 = "負一十二";
	public const BLUE_ICE = "負一十一";
	public const STRIPPED_OAK_LOG = "負一十";
	public const STRIPPED_DARK_OAK_LOG = "負九";
	public const STRIPPED_ACACIA_LOG = "負八";
	public const STRIPPED_JUNGLE_LOG = "負七";
	public const STRIPPED_BIRCH_LOG = "負六";
	public const STRIPPED_SPRUCE_LOG = "負五";
	public const PRISMARINE_BRICKS_STAIRS = "負四";
	public const DARK_PRISMARINE_STAIRS = "負三";
	public const PRISMARINE_STAIRS = "負二";

	public const AIR = "零";
	public const STONE = "一";
	public const GRASS = "二";
	public const DIRT = "三";
	public const COBBLESTONE = "四";
	public const PLANKS = "五", WOODEN_PLANKS = "五";
	public const SAPLING = "六";
	public const BEDROCK = "七";
	public const FLOWING_WATER = "八";
	public const STILL_WATER = "九", WATER = "九";
	public const FLOWING_LAVA = "十";
	public const LAVA = "十一", STILL_LAVA = "十一";
	public const SAND = "十二";
	public const GRAVEL = "十三";
	public const GOLD_ORE = "十四";
	public const IRON_ORE = "十五";
	public const COAL_ORE = "十六";
	public const LOG = "十七";
	public const LEAVES = "十八";
	public const SPONGE = "十九";
	public const GLASS = "二十";
	public const LAPIS_ORE = "二十一";
	public const LAPIS_BLOCK = "二十二";
	public const DISPENSER = "二十三";
	public const SANDSTONE = "二十四";
	public const NOTEBLOCK = "二十五", NOTE_BLOCK = "二十五";
	public const BED_BLOCK = "二十六";
	public const GOLDEN_RAIL = "二十七", POWERED_RAIL = "二十七";
	public const DETECTOR_RAIL = "二十八";
	public const STICKY_PISTON = "二十九";
	public const COBWEB = "三十", WEB = "三十";
	public const TALLGRASS = "三十一", TALL_GRASS = "三十一";
	public const DEADBUSH = "三十二", DEAD_BUSH = "三十二";
	public const PISTON = "三十三";
	public const PISTONARMCOLLISION = "三十四", PISTON_ARM_COLLISION = "三十四";
	public const WOOL = "三十五";
	public const ELEMENT_0 = "三十六";
	public const DANDELION = "三十七", YELLOW_FLOWER = "三十七";
	public const POPPY = "三十八", RED_FLOWER = "三十八";
	public const BROWN_MUSHROOM = "三十九";
	public const RED_MUSHROOM = "四十";
	public const GOLD_BLOCK = "四十一";
	public const IRON_BLOCK = "四十二";
	public const DOUBLE_STONE_SLAB = "四十三";
	public const STONE_SLAB = "四十四";
	public const BRICK_BLOCK = "四十五";
	public const TNT = "四十六";
	public const BOOKSHELF = "四十七";
	public const MOSSY_COBBLESTONE = "四十八", MOSS_STONE = "四十八";
	public const OBSIDIAN = "四十九";
	public const TORCH = "五十";
	public const FIRE = "五十一";
	public const MOB_SPAWNER = "五十二", MONSTER_SPAWNER = "五十二";
	public const OAK_STAIRS = "五十三", WOODEN_STAIRS = "五十三";
	public const CHEST = "五十四";
	public const REDSTONE_WIRE = "五十五";
	public const DIAMOND_ORE = "五十六";
	public const DIAMOND_BLOCK = "五十七";
	public const CRAFTING_TABLE = "五十八", WORKBENCH = "五十八";
	public const WHEAT_BLOCK = "五十九";
	public const FARMLAND = "六十";
	public const FURNACE = "六十一";
	public const BURNING_FURNACE = "六十二", LIT_FURNACE = "六十二";
	public const SIGN_POST = "六十三", STANDING_SIGN = "六十三";
	public const OAK_DOOR_BLOCK = "六十四", WOODEN_DOOR_BLOCK = "六十四";
	public const LADDER = "六十五";
	public const RAIL = "六十六";
	public const COBBLESTONE_STAIRS = "六十七", STONE_STAIRS = "六十七";
	public const WALL_SIGN = "六十八";
	public const LEVER = "六十九";
	public const STONE_PRESSURE_PLATE = "七十";
	public const IRON_DOOR_BLOCK = "七十一";
	public const WOODEN_PRESSURE_PLATE = "七十二";
	public const REDSTONE_ORE = "七十三";
	public const GLOWING_REDSTONE_ORE = "七十四", LIT_REDSTONE_ORE = "七十四";
	public const UNLIT_REDSTONE_TORCH = "七十五";
	public const LIT_REDSTONE_TORCH = "七十六", REDSTONE_TORCH = "七十六";
	public const STONE_BUTTON = "七十七";
	public const SNOW_LAYER = "七十八";
	public const ICE = "七十九";
	public const SNOW = "八十", SNOW_BLOCK = "八十";
	public const CACTUS = "八十一";
	public const CLAY_BLOCK = "八十二";
	public const REEDS_BLOCK = "八十三", SUGARCANE_BLOCK = "八十三";
	public const JUKEBOX = "八十四";
	public const FENCE = "八十五";
	public const PUMPKIN = "八十六";
	public const NETHERRACK = "八十七";
	public const SOUL_SAND = "八十八";
	public const GLOWSTONE = "八十九";
	public const PORTAL = "九十";
	public const JACK_O_LANTERN = "九十一", LIT_PUMPKIN = "九十一";
	public const CAKE_BLOCK = "九十二";
	public const REPEATER_BLOCK = "九十三", UNPOWERED_REPEATER = "九十三";
	public const POWERED_REPEATER = "九十四";
	public const INVISIBLEBEDROCK = "九十五", INVISIBLE_BEDROCK = "九十五";
	public const TRAPDOOR = "九十六", WOODEN_TRAPDOOR = "九十六";
	public const MONSTER_EGG = "九十七";
	public const STONEBRICK = "九十八", STONE_BRICK = "九十八", STONE_BRICKS = "九十八";
	public const BROWN_MUSHROOM_BLOCK = "九十九";
	public const RED_MUSHROOM_BLOCK = "一百";
	public const IRON_BARS = "一百零一";
	public const GLASS_PANE = "一百零二";
	public const MELON_BLOCK = "一百零三";
	public const PUMPKIN_STEM = "一百零四";
	public const MELON_STEM = "一百零五";
	public const VINE = "一百零六", VINES = "一百零六";
	public const FENCE_GATE = "一百零七", OAK_FENCE_GATE = "一百零七";
	public const BRICK_STAIRS = "一百零八";
	public const STONE_BRICK_STAIRS = "一百零九";
	public const MYCELIUM = "一百一十";
	public const LILY_PAD = "一百一十一", WATERLILY = "一百一十一", WATER_LILY = "一百一十一";
	public const NETHER_BRICK_BLOCK = "一百一十二";
	public const NETHER_BRICK_FENCE = "一百一十三";
	public const NETHER_BRICK_STAIRS = "一百一十四";
	public const NETHER_WART_PLANT = "一百一十五";
	public const ENCHANTING_TABLE = "一百一十六", ENCHANTMENT_TABLE = "一百一十六";
	public const BREWING_STAND_BLOCK = "一百一十七";
	public const CAULDRON_BLOCK = "一百一十八";
	public const END_PORTAL = "一百一十九";
	public const END_PORTAL_FRAME = "一百二十";
	public const END_STONE = "一百二十一";
	public const DRAGON_EGG = "一百二十二";
	public const REDSTONE_LAMP = "一百二十三";
	public const LIT_REDSTONE_LAMP = "一百二十四";
	public const DROPPER = "一百二十五";
	public const ACTIVATOR_RAIL = "一百二十六";
	public const COCOA = "一百二十七", COCOA_BLOCK = "一百二十七";
	public const SANDSTONE_STAIRS = "一百二十八";
	public const EMERALD_ORE = "一百二十九";
	public const ENDER_CHEST = "一百三十";
	public const TRIPWIRE_HOOK = "一百三十一";
	public const TRIPWIRE = "一百三十二", TRIP_WIRE = "一百三十二";
	public const EMERALD_BLOCK = "一百三十三";
	public const SPRUCE_STAIRS = "一百三十四";
	public const BIRCH_STAIRS = "一百三十五";
	public const JUNGLE_STAIRS = "一百三十六";
	public const COMMAND_BLOCK = "一百三十七";
	public const BEACON = "一百三十八";
	public const COBBLESTONE_WALL = "一百三十九", STONE_WALL = "一百三十九";
	public const FLOWER_POT_BLOCK = "一百四十";
	public const CARROTS = "一百四十一", CARROT_BLOCK = "一百四十一";
	public const POTATOES = "一百四十二", POTATO_BLOCK = "一百四十二";
	public const WOODEN_BUTTON = "一百四十三";
	public const MOB_HEAD_BLOCK = "一百四十四", SKULL_BLOCK = "一百四十四";
	public const ANVIL = "一百四十五";
	public const TRAPPED_CHEST = "一百四十六";
	public const LIGHT_WEIGHTED_PRESSURE_PLATE = "一百四十七";
	public const HEAVY_WEIGHTED_PRESSURE_PLATE = "一百四十八";
	public const COMPARATOR_BLOCK = "一百四十九", UNPOWERED_COMPARATOR = "一百四十九";
	public const POWERED_COMPARATOR = "一百五十";
	public const DAYLIGHT_DETECTOR = "一百五十一", DAYLIGHT_SENSOR = "一百五十一";
	public const REDSTONE_BLOCK = "一百五十二";
	public const NETHER_QUARTZ_ORE = "一百五十三", QUARTZ_ORE = "一百五十三";
	public const HOPPER_BLOCK = "一百五十四";
	public const QUARTZ_BLOCK = "一百五十五";
	public const QUARTZ_STAIRS = "一百五十六";
	public const DOUBLE_WOODEN_SLAB = "一百五十七";
	public const WOODEN_SLAB = "一百五十八";
	public const STAINED_CLAY = "一百五十九", STAINED_HARDENED_CLAY = "一百五十九", TERRACOTTA = "一百五十九";
	public const STAINED_GLASS_PANE = "一百六十";
	public const LEAVES2 = "一百六十一";
	public const LOG2 = "一百六十二";
	public const ACACIA_STAIRS = "一百六十三";
	public const DARK_OAK_STAIRS = "一百六十四";
	public const SLIME = "一百六十五", SLIME_BLOCK = "一百六十五";
	public const GLOW_STICK = "一百六十六";
	public const IRON_TRAPDOOR = "一百六十七";
	public const PRISMARINE = "一百六十八";
	public const SEALANTERN = "一百六十九", SEA_LANTERN = "一百六十九";
	public const HAY_BALE = "一百七十", HAY_BLOCK = "一百七十";
	public const CARPET = "一百七十一";
	public const HARDENED_CLAY = "一百七十二";
	public const COAL_BLOCK = "一百七十三";
	public const PACKED_ICE = "一百七十四";
	public const DOUBLE_PLANT = "一百七十五";
	public const STANDING_BANNER = "一百七十六";
	public const WALL_BANNER = "一百七十七";
	public const DAYLIGHT_DETECTOR_INVERTED = "一百七十八", DAYLIGHT_SENSOR_INVERTED = "一百七十八";
	public const RED_SANDSTONE = "一百七十九";
	public const RED_SANDSTONE_STAIRS = "一百八十";
	public const DOUBLE_STONE_SLAB2 = "一百八十一";
	public const STONE_SLAB2 = "一百八十二";
	public const SPRUCE_FENCE_GATE = "一百八十三";
	public const BIRCH_FENCE_GATE = "一百八十四";
	public const JUNGLE_FENCE_GATE = "一百八十五";
	public const DARK_OAK_FENCE_GATE = "一百八十六";
	public const ACACIA_FENCE_GATE = "一百八十七";
	public const REPEATING_COMMAND_BLOCK = "一百八十八";
	public const CHAIN_COMMAND_BLOCK = "一百八十九";
	public const HARD_GLASS_PANE = "一百九十";
	public const HARD_STAINED_GLASS_PANE = "一百九十一";
	public const CHEMICAL_HEAT = "一百九十二";
	public const SPRUCE_DOOR_BLOCK = "一百九十三";
	public const BIRCH_DOOR_BLOCK = "一百九十四";
	public const JUNGLE_DOOR_BLOCK = "一百九十五";
	public const ACACIA_DOOR_BLOCK = "一百九十六";
	public const DARK_OAK_DOOR_BLOCK = "一百九十七";
	public const GRASS_PATH = "一百九十八";
	public const FRAME_BLOCK = "一百九十九", ITEM_FRAME_BLOCK = "一百九十九";
	public const CHORUS_FLOWER = "二百";
	public const PURPUR_BLOCK = "二百零一";
	public const COLORED_TORCH_RG = "二百零二";
	public const PURPUR_STAIRS = "二百零三";
	public const COLORED_TORCH_BP = "二百零四";
	public const UNDYED_SHULKER_BOX = "二百零五";
	public const END_BRICKS = "二百零六";
	public const FROSTED_ICE = "二百零七";
	public const END_ROD = "二百零八";
	public const END_GATEWAY = "二百零九";

	public const MAGMA = "二百一十三";
	public const NETHER_WART_BLOCK = "二百一十四";
	public const RED_NETHER_BRICK = "二百一十五";
	public const BONE_BLOCK = "二百一十六";

	public const SHULKER_BOX = "二百一十八";
	public const PURPLE_GLAZED_TERRACOTTA = "二百一十九";
	public const WHITE_GLAZED_TERRACOTTA = "二百二十";
	public const ORANGE_GLAZED_TERRACOTTA = "二百二十一";
	public const MAGENTA_GLAZED_TERRACOTTA = "二百二十二";
	public const LIGHT_BLUE_GLAZED_TERRACOTTA = "二百二十三";
	public const YELLOW_GLAZED_TERRACOTTA = "二百二十四";
	public const LIME_GLAZED_TERRACOTTA = "二百二十五";
	public const PINK_GLAZED_TERRACOTTA = "二百二十六";
	public const GRAY_GLAZED_TERRACOTTA = "二百二十七";
	public const SILVER_GLAZED_TERRACOTTA = "二百二十八";
	public const CYAN_GLAZED_TERRACOTTA = "二百二十九";

	public const BLUE_GLAZED_TERRACOTTA = "二百三十一";
	public const BROWN_GLAZED_TERRACOTTA = "二百三十二";
	public const GREEN_GLAZED_TERRACOTTA = "二百三十三";
	public const RED_GLAZED_TERRACOTTA = "二百三十四";
	public const BLACK_GLAZED_TERRACOTTA = "二百三十五";
	public const CONCRETE = "二百三十六";
	public const CONCRETEPOWDER = "二百三十七", CONCRETE_POWDER = "二百三十七";
	public const CHEMISTRY_TABLE = "二百三十八";
	public const UNDERWATER_TORCH = "二百三十九";
	public const CHORUS_PLANT = "二百四十";
	public const STAINED_GLASS = "二百四十一";

	public const PODZOL = "二百四十三";
	public const BEETROOT_BLOCK = "二百四十四";
	public const STONECUTTER = "二百四十五";
	public const GLOWINGOBSIDIAN = "二百四十六", GLOWING_OBSIDIAN = "二百四十六";
	public const NETHERREACTOR = "二百四十七", NETHER_REACTOR = "二百四十七";
	public const INFO_UPDATE = "二百四十八";
	public const INFO_UPDATE2 = "二百四十九";
	public const MOVINGBLOCK = "二百五十", MOVING_BLOCK = "二百五十";
	public const OBSERVER = "二百五十一";
	public const STRUCTURE_BLOCK = "二百五十二";
	public const HARD_GLASS = "二百五十三";
	public const HARD_STAINED_GLASS = "二百五十四";
	public const RESERVED6 = "二百五十五";
	public const IRON_SHOVEL = "二百五十六";
	public const IRON_PICKAXE = "二百五十七";
	public const IRON_AXE = "二百五十八";
	public const FLINT_AND_STEEL = "二百五十九", FLINT_STEEL = "二百五十九";
	public const APPLE = "二百六十";
	public const BOW = "二百六十一";
	public const ARROW = "二百六十二";
	public const COAL = "二百六十三";
	public const DIAMOND = "二百六十四";
	public const IRON_INGOT = "二百六十五";
	public const GOLD_INGOT = "二百六十六";
	public const IRON_SWORD = "二百六十七";
	public const WOODEN_SWORD = "二百六十八";
	public const WOODEN_SHOVEL = "二百六十九";
	public const WOODEN_PICKAXE = "二百七十";
	public const WOODEN_AXE = "二百七十一";
	public const STONE_SWORD = "二百七十二";
	public const STONE_SHOVEL = "二百七十三";
	public const STONE_PICKAXE = "二百七十四";
	public const STONE_AXE = "二百七十五";
	public const DIAMOND_SWORD = "二百七十六";
	public const DIAMOND_SHOVEL = "二百七十七";
	public const DIAMOND_PICKAXE = "二百七十八";
	public const DIAMOND_AXE = "二百七十九";
	public const STICK = "二百八十";
	public const BOWL = "二百八十一";
	public const MUSHROOM_STEW = "二百八十二";
	public const GOLDEN_SWORD = "二百八十三", GOLD_SWORD = "二百八十三";
	public const GOLDEN_SHOVEL = "二百八十四", GOLD_SHOVEL = "二百八十四";
	public const GOLDEN_PICKAXE = "二百八十五", GOLD_PICKAXE = "二百八十五";
	public const GOLDEN_AXE = "二百八十六", GOLD_AXE = "二百八十六";
	public const STRING = "二百八十七";
	public const FEATHER = "二百八十八";
	public const GUNPOWDER = "二百八十九";
	public const WOODEN_HOE = "二百九十";
	public const STONE_HOE = "二百九十一";
	public const IRON_HOE = "二百九十二";
	public const DIAMOND_HOE = "二百九十三";
	public const GOLDEN_HOE = "二百九十四", GOLD_HOE = "二百九十四";
	public const SEEDS = "二百九十五", WHEAT_SEEDS = "二百九十五";
	public const WHEAT = "二百九十六";
	public const BREAD = "二百九十七";
	public const LEATHER_CAP = "二百九十八", LEATHER_HELMET = "二百九十八";
	public const LEATHER_CHESTPLATE = "二百九十九", LEATHER_TUNIC = "二百九十九";
	public const LEATHER_LEGGINGS = "三百", LEATHER_PANTS = "三百";
	public const LEATHER_BOOTS = "三百零一";
	public const CHAINMAIL_HELMET = "三百零二", CHAIN_HELMET = "三百零二";
	public const CHAINMAIL_CHESTPLATE = "三百零三", CHAIN_CHESTPLATE = "三百零三";
	public const CHAINMAIL_LEGGINGS = "三百零四", CHAIN_LEGGINGS = "三百零四";
	public const CHAINMAIL_BOOTS = "三百零五", CHAIN_BOOTS = "三百零五";
	public const IRON_HELMET = "三百零六";
	public const IRON_CHESTPLATE = "三百零七";
	public const IRON_LEGGINGS = "三百零八";
	public const IRON_BOOTS = "三百零九";
	public const DIAMOND_HELMET = "三百一十";
	public const DIAMOND_CHESTPLATE = "三百一十一";
	public const DIAMOND_LEGGINGS = "三百一十二";
	public const DIAMOND_BOOTS = "三百一十三";
	public const GOLDEN_HELMET = "三百一十四", GOLD_HELMET = "三百一十四";
	public const GOLDEN_CHESTPLATE = "三百一十五", GOLD_CHESTPLATE = "三百一十五";
	public const GOLDEN_LEGGINGS = "三百一十六", GOLD_LEGGINGS = "三百一十六";
	public const GOLDEN_BOOTS = "三百一十七", GOLD_BOOTS = "三百一十七";
	public const FLINT = "三百一十八";
	public const PORKCHOP = "三百一十九", RAW_PORKCHOP = "三百一十九";
	public const COOKED_PORKCHOP = "三百二十";
	public const PAINTING = "三百二十一";
	public const GOLDEN_APPLE = "三百二十二";
	public const SIGN = "三百二十三";
	public const OAK_DOOR = "三百二十四", WOODEN_DOOR = "三百二十四";
	public const BUCKET = "三百二十五";

	public const MINECART = "三百二十八";
	public const SADDLE = "三百二十九";
	public const IRON_DOOR = "三百三十";
	public const REDSTONE = "三百三十一", REDSTONE_DUST = "三百三十一";
	public const SNOWBALL = "三百三十二";
	public const BOAT = "三百三十三";
	public const LEATHER = "三百三十四";
	public const KELP = "三百三十五";
	public const BRICK = "三百三十六";
	public const CLAY = "三百三十七", CLAY_BALL = "三百三十七";
	public const REEDS = "三百三十八", SUGARCANE = "三百三十八";
	public const PAPER = "三百三十九";
	public const BOOK = "三百四十";
	public const SLIMEBALL = "三百四十一", SLIME_BALL = "三百四十一";
	public const CHEST_MINECART = "三百四十二", MINECART_WITH_CHEST = "三百四十二";

	public const EGG = "三百四十四";
	public const COMPASS = "三百四十五";
	public const FISHING_ROD = "三百四十六";
	public const CLOCK = "三百四十七";
	public const GLOWSTONE_DUST = "三百四十八";
	public const FISH = "三百四十九", RAW_FISH = "三百四十九";
	public const COOKED_FISH = "三百五十";
	public const DYE = "三百五十一";
	public const BONE = "三百五十二";
	public const SUGAR = "三百五十三";
	public const CAKE = "三百五十四";
	public const BED = "三百五十五";
	public const REPEATER = "三百五十六";
	public const COOKIE = "三百五十七";
	public const FILLED_MAP = "三百五十八";
	public const SHEARS = "三百五十九";
	public const MELON = "三百六十", MELON_SLICE = "三百六十";
	public const PUMPKIN_SEEDS = "三百六十一";
	public const MELON_SEEDS = "三百六十二";
	public const BEEF = "三百六十三", RAW_BEEF = "三百六十三";
	public const COOKED_BEEF = "三百六十四", STEAK = "三百六十四";
	public const CHICKEN = "三百六十五", RAW_CHICKEN = "三百六十五";
	public const COOKED_CHICKEN = "三百六十六";
	public const ROTTEN_FLESH = "三百六十七";
	public const ENDER_PEARL = "三百六十八";
	public const BLAZE_ROD = "三百六十九";
	public const GHAST_TEAR = "三百七十";
	public const GOLDEN_NUGGET = "三百七十一", GOLD_NUGGET = "三百七十一";
	public const NETHER_WART = "三百七十二";
	public const POTION = "三百七十三";
	public const GLASS_BOTTLE = "三百七十四";
	public const SPIDER_EYE = "三百七十五";
	public const FERMENTED_SPIDER_EYE = "三百七十六";
	public const BLAZE_POWDER = "三百七十七";
	public const MAGMA_CREAM = "三百七十八";
	public const BREWING_STAND = "三百七十九";
	public const CAULDRON = "三百八十";
	public const ENDER_EYE = "三百八十一";
	public const GLISTERING_MELON = "三百八十二", SPECKLED_MELON = "三百八十二";
	public const SPAWN_EGG = "三百八十三";
	public const BOTTLE_O_ENCHANTING = "三百八十四", EXPERIENCE_BOTTLE = "三百八十四";
	public const FIREBALL = "三百八十五", FIRE_CHARGE = "三百八十五";
	public const WRITABLE_BOOK = "三百八十六";
	public const WRITTEN_BOOK = "三百八十七";
	public const EMERALD = "三百八十八";
	public const FRAME = "三百八十九", ITEM_FRAME = "三百八十九";
	public const FLOWER_POT = "三百九十";
	public const CARROT = "三百九十一";
	public const POTATO = "三百九十二";
	public const BAKED_POTATO = "三百九十三";
	public const POISONOUS_POTATO = "三百九十四";
	public const EMPTYMAP = "三百九十五", EMPTY_MAP = "三百九十五", MAP = "三百九十五";
	public const GOLDEN_CARROT = "三百九十六";
	public const MOB_HEAD = "三百九十七", SKULL = "三百九十七";
	public const CARROTONASTICK = "三百九十八", CARROT_ON_A_STICK = "三百九十八";
	public const NETHERSTAR = "三百九十九", NETHER_STAR = "三百九十九";
	public const PUMPKIN_PIE = "四百";
	public const FIREWORKS = "四百零一";
	public const FIREWORKSCHARGE = "四百零二", FIREWORKS_CHARGE = "四百零二";
	public const ENCHANTED_BOOK = "四百零三";
	public const COMPARATOR = "四百零四";
	public const NETHERBRICK = "四百零五", NETHER_BRICK = "四百零五";
	public const NETHER_QUARTZ = "四百零六", QUARTZ = "四百零六";
	public const MINECART_WITH_TNT = "四百零七", TNT_MINECART = "四百零七";
	public const HOPPER_MINECART = "四百零八", MINECART_WITH_HOPPER = "四百零八";
	public const PRISMARINE_SHARD = "四百零九";
	public const HOPPER = "四百一十";
	public const RABBIT = "四百一十一", RAW_RABBIT = "四百一十一";
	public const COOKED_RABBIT = "四百一十二";
	public const RABBIT_STEW = "四百一十三";
	public const RABBIT_FOOT = "四百一十四";
	public const RABBIT_HIDE = "四百一十五";
	public const HORSEARMORLEATHER = "四百一十六", HORSE_ARMOR_LEATHER = "四百一十六", LEATHER_HORSE_ARMOR = "四百一十六";
	public const HORSEARMORIRON = "四百一十七", HORSE_ARMOR_IRON = "四百一十七", IRON_HORSE_ARMOR = "四百一十七";
	public const GOLDEN_HORSE_ARMOR = "四百一十八", GOLD_HORSE_ARMOR = "四百一十八", HORSEARMORGOLD = "四百一十八", HORSE_ARMOR_GOLD = "四百一十八";
	public const DIAMOND_HORSE_ARMOR = "四百一十九", HORSEARMORDIAMOND = "四百一十九", HORSE_ARMOR_DIAMOND = "四百一十九";
	public const LEAD = "四百二十";
	public const NAMETAG = "四百二十一", NAME_TAG = "四百二十一";
	public const PRISMARINE_CRYSTALS = "四百二十二";
	public const MUTTON = "四百二十三", MUTTONRAW = "四百二十三", MUTTON_RAW = "四百二十三", RAW_MUTTON = "四百二十三";
	public const COOKED_MUTTON = "四百二十四", MUTTONCOOKED = "四百二十四", MUTTON_COOKED = "四百二十四";
	public const ARMOR_STAND = "四百二十五";
	public const END_CRYSTAL = "四百二十六";
	public const SPRUCE_DOOR = "四百二十七";
	public const BIRCH_DOOR = "四百二十八";
	public const JUNGLE_DOOR = "四百二十九";
	public const ACACIA_DOOR = "四百三十";
	public const DARK_OAK_DOOR = "四百三十一";
	public const CHORUS_FRUIT = "四百三十二";
	public const CHORUS_FRUIT_POPPED = "四百三十三";
	public const BANNER_PATTERN = "四百三十四";

	public const DRAGON_BREATH = "四百三十七";
	public const SPLASH_POTION = "四百三十八";

	public const LINGERING_POTION = "四百四十一";
	public const SPARKLER = "四百四十二";
	public const COMMAND_BLOCK_MINECART = "四百四十三", MINECART_WITH_COMMAND_BLOCK = "四百四十三";
	public const ELYTRA = "四百四十四";
	public const SHULKER_SHELL = "四百四十五";
	public const BANNER = "四百四十六";
	public const MEDICINE = "四百四十七";
	public const BALLOON = "四百四十八";
	public const RAPID_FERTILIZER = "四百四十九";
	public const TOTEM = "四百五十";
	public const BLEACH = "四百五十一";
	public const IRON_NUGGET = "四百五十二";
	public const ICE_BOMB = "四百五十三";

	public const TRIDENT = "四百五十五";

	public const BEETROOT = "四百五十七";
	public const BEETROOT_SEEDS = "四百五十八";
	public const BEETROOT_SOUP = "四百五十九";
	public const RAW_SALMON = "四百六十", SALMON = "四百六十";
	public const CLOWNFISH = "四百六十一";
	public const PUFFERFISH = "四百六十二";
	public const COOKED_SALMON = "四百六十三";
	public const DRIED_KELP = "四百六十四";
	public const NAUTILUS_SHELL = "四百六十五";
	public const APPLEENCHANTED = "四百六十六", APPLE_ENCHANTED = "四百六十六", ENCHANTED_GOLDEN_APPLE = "四百六十六";
	public const HEART_OF_THE_SEA = "四百六十七";
	public const TURTLE_SHELL_PIECE = "四百六十八";
	public const TURTLE_HELMET = "四百六十九";
	public const PHANTOM_MEMBRANE = "四百七十";
	public const CROSSBOW = "四百七十一";
	public const SPRUCE_SIGN = "四百七十二";
	public const BIRCH_SIGN = "四百七十三";
	public const JUNGLE_SIGN = "四百七十四";
	public const ACACIA_SIGN = "四百七十五";
	public const DARKOAK_SIGN = "四百七十六";
	public const SWEET_BERRIES = "四百七十七";

	public const COMPOUND = "四百九十九";
	public const RECORD_13 = "五百";
	public const RECORD_CAT = "五百零一";
	public const RECORD_BLOCKS = "五百零二";
	public const RECORD_CHIRP = "五百零三";
	public const RECORD_FAR = "五百零四";
	public const RECORD_MALL = "五百零五";
	public const RECORD_MELLOHI = "五百零六";
	public const RECORD_STAL = "五百零七";
	public const RECORD_STRAD = "五百零八";
	public const RECORD_WARD = "五百零九";
	public const RECORD_11 = "五百一十";
	public const RECORD_WAIT = "五百一十一";

	public const SHIELD = "五百一十三";

}
