#Due to GitHub awkwardness, it's not easy to reduce the review requirement for collaborators.
#Our policy is that 2 collaborators should be aware of every change.
#For outside PRs, this means 2 collaborator reviews.
#For PRs made by collaborators, this means 1 reviewer + the author.
#We trust that collaborators don't need as much oversight.
name: Auto approve collaborator PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: write

jobs:
  approve:
    name: Auto approve
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR author has write access
        id: check-permission
        uses: actions-cool/check-user-permission@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          require: write
          username: ${{ github.event.pull_request.user.login }}
          #technically this would be fine for dependabot but generally bots don't count as team members
          check-bot: true

      - name: Cache previous approvals
        uses: actions/cache@v3
        with:
          path: .github/approvals
          key: ${{ github.event.pull_request.head.sha }}

      - name: Check if PR has been approved before
        id: check-approval
        run: |
          if [ -f ".github/approvals/${{ github.event.pull_request.head.sha }}" ]; then
            echo "approved=true" >> $GITHUB_ENV
          else
            echo "approved=false" >> $GITHUB_ENV
          fi

      - name: Approve PR if authorized
        if: steps.check-permission.outputs.require-result == 'true' && steps.check-permission.outputs.check-result == 'false' && env.approved == 'false'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}

      - name: Save approval state
        if: steps.check-permission.outputs.require-result == 'true' && steps.check-permission.outputs.check-result == 'false' && env.approved == 'false'
        run: |
          mkdir -p .github/approvals
          touch .github/approvals/${{ github.event.pull_request.head.sha }}